"""Add plaid_access_token

Revision ID: 9f77cd2d04dd
Revises: b5254ba7753e
Create Date: 2026-06-24 11:33:45.229652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f77cd2d04dd'
down_revision: Union[str, Sequence[str], None] = 'b5254ba7753e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plaid_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plaid_access_token')
    # ### end Alembic commands ###
