"""add auth

Revision ID: b5254ba7753e
Revises: 77ede71c6228
Create Date: 2026-06-21 13:24:27.594045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5254ba7753e'
down_revision: Union[str, Sequence[str], None] = '77ede71c6228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Wipe existing data as requested by user to allow non-nullable FK insertion ###
    op.execute('TRUNCATE TABLE predictions CASCADE')
    op.execute('TRUNCATE TABLE customers CASCADE')
    op.execute('TRUNCATE TABLE users CASCADE')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('predictions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'predictions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.alter_column('predictions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('predictions', 'user_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
